### ISSUE TITLE
connector with 2 flow variables

### ISSUE THREAD

**Issue by johhell** [ModiaSim/ModiaLang.jl#2]
I tried a simple electrical example with a voltage source and 2 resistors using complex quantities. For the connector I used 2 ```potential``` and 2 ```flow``` variables. The results was not correct.

## used elements
```julia
Cpin = Model(
    vRe = potential,
    vIm = potential,
    iRe = flow,
    iIm = flow
    )

ConePort = Model( 
    p = Cpin,
    n = Cpin,
    voltsRe = Var(),
    voltsIm = Var(),
    ampsRe = Var(),
    ampsIm = Var(),
    equations = :[
        voltsRe = p.vRe - n.vRe
        voltsIm = p.vIm - n.vIm
        0 = p.iRe + n.iRe
        0 = p.iIm + n.iIm
        ampsRe = p.iRe
        ampsIm = p.iIm
        ] )

Cresistor = ConePort | 	Model( 
    R = Var(parameter=true, value=1.11),
    equations = :[ 
        R*ampsRe = voltsRe
        R*ampsIm = voltsIm
        ] )
```
The full example here: [myComplex.jl.txt](https://github.com/ModiaSim/ModiaLang.jl/files/6984746/myComplex.jl.txt)

## simulation results

The connection equations for the potential variables are correct, but for flow variables both are used in the equation - see below. 
The system breaks down into 2 independent parts (Re, Im), so the equation should only have Re or Im variables

### connection equations
```julia
connect equations in TTTT:
  Volts.p.vRe = R1.p.vRe
  Volts.p.vIm = R1.p.vIm
  0 = ((Volts.p.iRe + Volts.p.iIm) + R1.p.iRe) + R1.p.iIm   #--> WRONG
  R1.n.vRe = R2.p.vRe
  R1.n.vIm = R2.p.vIm
  0 = ((R1.n.iRe + R1.n.iIm) + R2.p.iRe) + R2.p.iIm   #--> WRONG
  R2.n.vRe = Volts.n.vRe
  R2.n.vIm = Volts.n.vIm
  Volts.n.vRe = ground.pin.vRe
  Volts.n.vIm = ground.pin.vIm
  0 = ((((R2.n.iRe + R2.n.iIm) + Volts.n.iRe) + Volts.n.iIm) + ground.pin.iRe) + ground.pin.iIm     #--> WRONG
```

## modification

I made some modification in _ModelCollections.jl_ to create flow-Connection equations for each single flow variable in the connector. 
It works.

[ModelCollections.jl.txt](https://github.com/ModiaSim/ModiaLang.jl/files/6984756/ModelCollections.jl.txt)

**remark:**  Sorry for my programming style. Working >20y with MODELICA, but only 20day with Julia.

### correct connection equations
```julia
Connect equations in TTTT:
  Volts.p.vRe = R1.p.vRe
  Volts.p.vIm = R1.p.vIm
  0 = Volts.p.iRe + R1.p.iRe
  0 = Volts.p.iIm + R1.p.iIm
  R1.n.vRe = R2.p.vRe
  R1.n.vIm = R2.p.vIm
  0 = R1.n.iRe + R2.p.iRe
  0 = R1.n.iIm + R2.p.iIm
  R2.n.vRe = Volts.n.vRe
  R2.n.vIm = Volts.n.vIm
  Volts.n.vRe = ground.pin.vRe
  Volts.n.vIm = ground.pin.vIm
  0 = (R2.n.iRe + Volts.n.iRe) + ground.pin.iRe
  0 = (R2.n.iIm + Volts.n.iIm) + ground.pin.iIm
```

## versions

Julia: Version 1.5.3 (2020-11-09)
ModiaLang : version = "0.8.1"
Modia:  version = "0.5.1-dev"

**Comment by HildingElmqvist** [comment]
You are correct, that you found an issue with this partial implementation of connect semantics. I have started to generalize it. 

In the mean time, you can use your implementation or you can use Complex numbers:

`ComplexTest = Model(
    p = Pin,
    n = Pin,
    equations = :[
        connect(p, n)
        p.v = Complex(1.0)
        p.i = Complex(0.9, 0.1)
        n_i_im = imag(n.i)
    ]
)

complexTest = @instantiateModel(ComplexTest, log=true)
simulate!(complexTest, stopTime=1)
plot(complexTest, ("n.i", "n_i_im"))`

Note that to plot the imaginary part, you must introduce an auxiliary variable and use the imag() function.

**Comment by johhell** [comment]
Using Complex number in equation is possible, but to solve a system of equations, Complex has to be split into REAL and IMAG parts. The same for the der() operator.
Modia is extreme powerful and offers high level of flexibility. Great work.
